spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${USER_MANAGEMENT_URL:http://localhost:8089}/oauth2/jwks
          
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          timeout: '5000'
          auth: 'true'
          connectiontimeout: '5000'
          writetimeout: '5000'
    host: smtp.gmail.com
    username: mohamedelfadhel.naouar@esprit.tn
    password: 
    port: '587'

mail:
  smtp:
    debug: 'true'
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761}/eureka
      
server:
  port: 8085

debug: true   

